services:
  - type: static
    name: futurepath-ai
    env: static
    buildCommand: npm install && npm run build
    publishDir: dist
    autoDeploy: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
